apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: aws
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: wge
  path: ./mgmt-cluster/bases/aws
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: global-config
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
