apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Provider
metadata:
  name: github-status
  namespace: ${nameSpace}
spec:
  type: github
  address: https://github.com/${GitHubOrg}/${GitHubRepo}
  secretRef:
    name: github-repo-write-token
---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Alert
metadata:
  name: github-status
  namespace: ${nameSpace}
spec:
  providerRef:
    name: github-status
  eventSources:
    - kind: Kustomization
      name: "*"
      namespace: ${nameSpace}
