apiVersion: v1
kind: ServiceAccount
metadata:
  name: tf-runner
  namespace: ${nameSpace}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tf-runner-role
  namespace: ${nameSpace}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - "coordination.k8s.io"
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tf-runner
  namespace: ${nameSpace}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tf-runner-role
subjects:
- kind: ServiceAccount
  name: tf-runner