apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: clusters
  namespace: flux-system
spec:
  interval: 10m0s
  ref:
    branch: main
  url: https://github.com/ww-gitops/clusters
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: global-config
  namespace: flux-system
spec:
  interval: 10m0s
  ref:
    branch: main
  url: https://github.com/ww-gitops/global-config
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-components
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./mgmt-cluster/addons/flux
  prune: true
  sourceRef:
    kind: GitRepository
    name: global-config
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m0s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: https://github.com/ww-gitops/paulc-macbook
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m0s
  path: ././mgmt-cluster/flux
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

